---
ocm_protect_keys: true
ocm_protected_keys:
  - 'name'
  - 'clusterID'
  - 'cloud'
  - 'vendor'
  - 'local-cluster'
  - 'openshiftVersion'
  - 'installer.name'
  - 'installer.namespace'
  - 'feature.open-cluster-management.io/addon-application-manager'
  - 'feature.open-cluster-management.io/addon-cert-policy-controller'
  - 'feature.open-cluster-management.io/addon-iam-policy-controller'
  - 'feature.open-cluster-management.io/addon-policy-controller'
  - 'feature.open-cluster-management.io/addon-search-collector'
  - 'feature.open-cluster-management.io/addon-work-manager'
