---
- name: "[HUB] Verify valid cluster name"
  assert:
    that: ocm_managedcluster_name is regex('^[a-z0-9]([-a-z0-9]*[a-z0-9])?$')
    fail_msg: "ocm_managedcluster_name failed regex validation"
    success_msg: "{{ ocm_managedcluster_name }} is valid"

- name: "[HUB] Create ManagedCluster"
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ ocm_hub_kubeconfig }}"
    template: managedcluster.yml
    wait: true
    wait_condition:
      type: 'HubAcceptedManagedCluster'
      reason: 'HubClusterAdminAccepted'
      status: 'True'
    wait_timeout: 60

- name: "[HUB] Create KlusterAddonConfig"
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ ocm_hub_kubeconfig }}"
    template: klusterletaddonconfig.yml
