---
- name: Hub Cluster Tasks
  include_tasks: hub_setup.yml
  when:
    - ocm_hub_kubeconfig is defined
    - ocm_managedcluster_kubeconfig is not defined

- name: Managed Cluster Tasks
  include_tasks: managedcluster_setup.yml
  when:
    - ocm_hub_kubeconfig is defined
    - ocm_managedcluster_kubeconfig is defined