---
- name: Setup Red Hat Advanced Cluster Management (RHACM) Operator
  block:
    - name: Create Namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: open-cluster-management
    - name: Create OperatorGroup
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: open-cluster-management-group
            namespace: open-cluster-management
          spec:
            targetNamespaces:
              - open-cluster-management
    - name: Create Operator Subscription
      kubernetes.core.k8s:
        state: present
        template: operator.yml
        wait: true
        wait_condition:
          type: 'CatalogSourcesUnhealthy'
          reason: 'AllCatalogSourcesHealthy'
          status: 'False'

- name: Setup MultiClusterHub (MCH) instance
  kubernetes.core.k8s:
    state: present
    template: multiclusterhub.yml
    wait: true
    wait_condition:
      type: 'Complete'
      reason: 'ComponentsAvailable'
      status: 'True'
    wait_timeout: 300
