---
apiVersion: v1
kind: Secret
metadata:
  name: thanoscreds
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: {{ ocm_s3_bucket }}
      endpoint: {{ ocm_s3_endpoint }}
      signature_version2: false
      insecure: true
      access_key: {{ ocm_s3_access_key }}
      secret_key: {{ ocm_s3_secret_key }}
      http_config:
        insecure_skip_verify: false
...
