---
- name: "Verify valid cluster name"
  assert:
    that: ocm_managedcluster_name is regex('^[a-z0-9]([-a-z0-9]*[a-z0-9])?$')
    fail_msg: "ocm_managedcluster_name failed regex validation"
    success_msg: "{{ ocm_managedcluster_name }} is valid"

- name: Get Labels from Cluster
  set_fact:
    ocm_cluster_labels: "{{ lookup('kubernetes.core.k8s', kubeconfig=ocm_hub_kubeconfig, api_version='cluster.open-cluster-management.io/v1', kind='ManagedCluster', resource_name=ocm_managedcluster_name) | json_query(query) }}"
  vars:
    query: "metadata.labels"

- name: Set Theory Calculations
  vars:
    keys_userlist_all: "{{ ocm_user_labels.keys() | list }}"
    keys_clusterlist_all: "{{ ocm_cluster_labels.keys() | list }}"
    keys_userlist_filtered: "{{ keys_userlist_all | difference(ocm_protected_keys) }}"
    keys_clusterlist_filtered: "{{ keys_clusterlist_all | difference(ocm_protected_keys) }}"
    keys_userlist_uniq: "{{ keys_userlist_all | difference(keys_clusterlist_all) }}"
    keys_userlist_uniq_filtered: "{{ keys_userlist_uniq | difference(ocm_protected_keys) }}"
  set_fact:
    ocm_keys_userlist_all: "{{ keys_userlist_all }}"
    ocm_keys_clusterlist_all: "{{ keys_clusterlist_all }}"
    ocm_keys_userlist_filtered: "{{ keys_userlist_filtered }}"
    ocm_keys_clusterlist_filtered: "{{ keys_clusterlist_filtered }}"
    ocm_keys_userlist_uniq: "{{ keys_userlist_uniq }}"
    ocm_keys_userlist_uniq_filtered: "{{ keys_userlist_uniq_filtered }}"

- name: Replace
  vars:
    clusterlist_delete_keys: "{{ ocm_protect_keys | ternary(ocm_keys_clusterlist_filtered, ocm_keys_clusterlist_all) }}"
    userlist_update_keys: "{{ ocm_protect_keys | ternary(ocm_keys_userlist_filtered, ocm_keys_userlist_all) }}"
  block:
    - name: '[REPLACE] Clear ManagedCluster Labels'
      kubernetes.core.k8s:
        state: patched
        kubeconfig: "{{ ocm_hub_kubeconfig }}"
        template: mc_delete_label.yml
      loop: "{{ clusterlist_delete_keys }}"

    - name: '[REPLACE] Add User Labels to ManagedCluster'
      kubernetes.core.k8s:
        state: patched
        kubeconfig: "{{ ocm_hub_kubeconfig }}"
        template: mc_update_label.yml
      loop: "{{ userlist_update_keys }}"
  when: ocm_merge_type == 'replace'

- name: Update
  vars:
    userlist_update_keys: "{{ ocm_protect_keys | ternary(ocm_keys_userlist_filtered, ocm_keys_userlist_all) }}"
  block:
    - name: '[UPDATE] Update User Labels to ManagedCluster'
      kubernetes.core.k8s:
        state: patched
        kubeconfig: "{{ ocm_hub_kubeconfig }}"
        template: mc_update_label.yml
      loop: "{{ userlist_update_keys }}"
  when: ocm_merge_type == 'update'

- name: Preserve
  vars:
    userlist_update_keys: "{{ ocm_protect_keys | ternary(ocm_keys_userlist_uniq_filtered, ocm_keys_userlist_uniq) }}"
  block:
    - name: '[PRESERVE] Update User Labels to ManagedCluster'
      kubernetes.core.k8s:
        state: patched
        kubeconfig: "{{ ocm_hub_kubeconfig }}"
        template: mc_update_label.yml
      loop: "{{ userlist_update_keys }}"
  when: ocm_merge_type == 'preserve'

- name: Delete
  vars:
    userlist_delete_keys: "{{ ocm_protect_keys | ternary(ocm_keys_userlist_filtered, ocm_keys_userlist_all) }}"
  block:
    - name: '[DELETE] Remove ManagedCluster Labels'
      kubernetes.core.k8s:
        state: patched
        kubeconfig: "{{ ocm_hub_kubeconfig }}"
        template: mc_delete_label.yml
      loop: "{{ userlist_delete_keys }}"
  when: ocm_merge_type == 'delete'
