name: Official Galaxy Publish
on:
  # manual trigger
  workflow_dispatch:

env:
  NAMESPACE: stolostron
  COLLECTION_NAME: core

jobs:
  check_publish:
    name: Galaxy Publish
    strategy:
      matrix:
        ansible:
          - stable-2.12
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set collection version
        run: |
          echo "COLLECTION_VERSION=$(cat ./galaxy.yml | grep 'version: ' | cut -d ' ' -f 2)" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install ansible-base (${{ matrix.ansible }})
        run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check
      - name: Install galaxy-importer
        run: pip install galaxy-importer --disable-pip-version-check
      - name: Build collection artifact file
        run: ansible-galaxy collection build
      - name: Run galaxy-importer
        run: python -m galaxy_importer.main ${{env.NAMESPACE}}-${{env.COLLECTION_NAME}}-${{env.COLLECTION_VERSION}}.tar.gz
      - name: Publish to Galaxy
        run: ansible-galaxy collection publish ${{env.NAMESPACE}}-${{env.COLLECTION_NAME}}-${{env.COLLECTION_VERSION}}.tar.gz --token ${{ secrets.GALAXY_API_KEY }}
      